### ISSUE TITLE
Soporta Jaspersoft Studio 622

### ISSUE THREAD

**Issue by cabustos** [agmoyano/node-jasper#24]
Saludos una pregunta este soporta jaspersoft Studio 622 o solo la version que esta en el ejemplo?

**Comment by agmoyano** [comment]
Hola, no he testeado con versiones superiores al ejemplo. Calculo que ya debes haber probado si funciona o no. Por favor, has un comentario de como fueron los resultados.

Saludos.

**Comment by navtek** [comment]
Hola, he probado con Jasperreports 6.3.1 y no funciona puesto que el modulo busca que exista la carpeta lib y el equipo de Jaspersoft ha cambiado la estructura del proyecto, si uso la versión que viene en el ejemplo funciona de maravilla

**Comment by navtek** [comment]
Hola hice mis pruebas, de hecho el equipo de Jaspersoft no ha cambiado nada, solo ha quitado la carpeta de lib, logre generar mi propia carpeta de lib recompilando el proyecto que se puede bajar desde el repositorio que se encuentra aquí mismo en GitHub, descomprimí el .jar generado y saque todos los .jar que estaban dentro de la carpeta creada a una carpeta llamada lib, la única librería que no venía (por algún motivo extraño) es la de log4j, se encontraba la dependencia pero no se generó, esa librería la extraje de la versión de jasperreports que se usa en el ejemplo. La prueba la hice con Jasperreports 6.3.1 y ya no me marcó error, el reporte en pdf no se creó pero creo que es porque estoy haciendo algo mal y es meramente de mi reporte.
