### ISSUE TITLE
Example with angular2

### ISSUE THREAD

**Issue by capcar** [agmoyano/node-jasper#29]
Hello,
can I use this component in one project, wrotten  in angular2?
If yes, how I can do it?
Thanks

**Comment by agmoyano** [comment]
Hello, sorry but I don't think it can be used with angular... It was
written as part of your backend with node, not to work directly with
frontend (it needs access to file system and Java runtime, that you usually
cannot do in browsers).

If you have an API with your app, this can be a part of it, or you could
create a new API in node just for this.

Good Luck!

**Comment by capcar** [comment]
I have tried to create one server, using node-jasper but, when I install node-jasper I obtain this:
`gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\capizzi\Desktop\sirsipa svn\29_01SIRSIPA\03_ProgettiSviluppo\PROTOTIPO_FINALE\PrototipoIntegrato_OR8\00_Lecce_v1\jaspertest\server\node_modules\java
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node-jasper"
npm ERR! node v6.9.4
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.7.2 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script 'node-gyp rebuild'.`

I have installed node-gyp and windows-build-tools....what am I  doing wrong?

**Comment by agmoyano** [comment]
That problem is related to [java](https://www.npmjs.com/package/java) project. Please check that project [issues](https://github.com/joeferner/node-java/issues) or [google group](https://groups.google.com/forum/#!forum/node-java)

You said you installed node-gyp and windows-build-tools, do you have Java installed too?

Good Luck!

**Comment by capcar** [comment]
Yes, I have installed java, too....
I am trying in the forums.
Thanks
