### ISSUE TITLE
Problem when installing on node 8.4.0

### ISSUE THREAD

**Issue by tiagowippel** [agmoyano/node-jasper#33]
Hi,

strangely when a I install node-jasper on node 8 it try to install java@0.7.2 package (and breaks), but according with package.json on node-jasper it should install java@0.8.0 wich installs correctly.. (tested cloning the repo).

Maybe an update of npm package is missing...

**Comment by tiagowippel** [comment]
Hey guys, 
Is someone having trouble with this too ?

**Comment by joevchs** [comment]
Same here, node v8.9.1 and npm v5.5.1
npm ERR! Failed at the java@0.7.2 install script.

Did you find a solution?

**Comment by KThen** [comment]
Leaving a comment here to add to this issue.
npm install --save node-jasper failed to compile java files.

node version: 8.11.3
npm version: 5.6.0
os: centos

However, if changing the dependency of java in package.json to exactly 0.8.0 works.
Haven't got the time to try with anything above java@^0.8.0 yet.

**Comment by agmoyano** [comment]
Sorry guys it took so long.. I updated npm version to add java@0.8.0

**Comment by agmoyano** [comment]
Please let me know if this fixes the issue and I'll close it.
