### ISSUE TITLE
Jasper Report Node Module (perfx-node-jasper module)

### ISSUE THREAD

**Issue by nohaso** [agmoyano/node-jasper#35]
Hi, I am having the error below when trying to run an **Express/Node App** and I have been able to narrow the problem to my attempt to include Jasper Reporting functionality using the **perfx-node-jasper** module (https://www.npmjs.com/package/perfx-node-jasper). 

For the **path** in the **options** object, I used the **jasperreports-5.6.1 directory** from **jasperreports-5.6.1-project.tar.gz**.

The Jasper Reporting functionality (using the perfx-node-jasper module) **worked successfully on my Windows machine**, but when I tried to run the same on a Linux Machine (Centos 6) I get the error below (**view the attached log file for more details**):

# # A fatal error has been detected by the Java Runtime Environment: # # SIGBUS (0x7) at pc=0x00007fac09012f02 , pid=16158, tid=0x00007fac40a19720

## JRE version: (8.0_144-b01) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame: # j java.lang.Object.()V+0
## An error report file with more information is saved as:
# /home/nohaso/node-postgres-promises/hs_err_pid16158.log

**View the attached log file for more details:**
[hs_err_pid905629.log](https://github.com/agmoyano/node-jasper/files/1633954/hs_err_pid905629.log)

**Comment by jhonny983** [comment]
Hi, Can you solve this??
