### ISSUE TITLE
Newbie for node-jasper

### ISSUE THREAD

**Issue by thearabbit** [agmoyano/node-jasper#37]
I am a newbie of `Jasper Report + Node`.
Now I base on `Meteor, Mongo, Vue`.
Could has any share/example?

**Comment by agmoyano** [comment]
In Readme.md you've got a full example, but the basics are as follow:

1. configure your jasper instance where you have to specify the following:
    1.  a path to jasperreports-x.x.x (x.x.x is version number) unzipped from jasperreports-x.x.x-project.tar.gz.
    1. If your report uses database connection, you have to specify drivers.
    1. Again, if your report uses database, you have to specify connections in 'conn' section.
    1. Configure your reports with jasper file path
1. Use your configured node-jasper instance to generate pdf `jasper.pdf(data)`. _data_ should be as explained in Readme.md, in _export_ definition.

Cheers
