### ISSUE TITLE
How to Custom fonts embed Export pdf 

### ISSUE THREAD

**Issue by 4Chart** [agmoyano/node-jasper#39]
Hello
 I want Custom fonts embed Export pdf but can't find font 

 What should I do?

**Comment by agmoyano** [comment]
If you installed the font in your OS and can't use it's, I think you should place your fonts un your JVM directory... in Ubuntu, it would be in /usr/lib/jvm/<your JVM version>

Hope ir helps

**Comment by agmoyano** [comment]
I'm sorry it didn't help... please check [java project issues](https://github.com/joeferner/node-java) to see if you can find a solution.

Regards.
