### ISSUE TITLE
I can render Report

### ISSUE THREAD

**Issue by Arruebo** [agmoyano/node-jasper#40]
Hello, could you please explain me because I can export my report? When call de endpoint with the function to export jasper to report, java is executed, but not have any response after call jasper.pdf():

var fs = require("fs");
var jasper = require("node-jasper")({
  path: "../../lib/jasperreports-6.5.1/",
  tmpPath: "../../reports/temp",
  reports: {
    estados_de_obra: {
      jasper: "../../reports/estados-de-obra.jasper",
      conn: "in_memory_json"
    }
  }
});
class ReportesController {
  static printEstadosDeObra(req, res, next) {
    var reportData = {
      report: "estados_de_obra",
      data: {},
      dataset: [
        {
          estadoObra: "Terminada",
          nombreObra: "Autopista"
        },
        {
          estadoObra: "En proceso",
          nombreObra: "Plaza Vieja"
        }
      ]
    };
    var pdf = jasper.pdf(reportData);
    var fileName = "Estados-de-Obra.pdf";
    ruta = __dirname + "/reports/" + fileName + ".pdf";
    console.log("Before fs.writeFile");
    fs.writeFile(ruta, pdf, function(err, result) {
      if (err) {
        console.log("Error", err);
        return next({ status: 450, pathError: req.url, errorCode: err });
      } else {
        console.log("Result", result, " The file was saved!");
        return next(result);
      }
    });
  }
}
module.exports = ReportesController;

**Comment by agmoyano** [comment]
Hello, is the pdf been written?.. I mean, do you see if Estados-de-Obra.pdf file exists?

On the other hand, because of the footprint of your function "printEstadosDeObra(req, res, next)", it seems you are using it as a middleware on express or connect.. It seems you could just do the following:

```javascript
var pdf = jasper.pdf(reportData);
res.set({
	'Content-type': 'application/pdf',
	'Content-Length': pdf.length
});
res.send(pdf);
```

instead of writing it to a file..
