### ISSUE TITLE
PDF no renderiza bien

### ISSUE THREAD

**Issue by rommelmemin7** [agmoyano/node-jasper#42]
Saludos, en jasper cuando ejecuto el reporte, me muestra el texto alineado y justificado como lo he programado, pero cuando lo ejecuto desde node, no me funciona ninguna alineación, talvez alguna solución??

**Comment by agmoyano** [comment]
Hola, no creo que el problema se de node-jasper.. toda esa información está dentro del archivo .jasper, y no debería variar dependiendo de quien la ejecuta.

Habrás puesto la misma versión del archivo .jasper?

Saludos.
