### ISSUE TITLE
Error api request

### ISSUE THREAD

**Issue by rennan0** [agmoyano/node-jasper#76]
I want to send a report created at Jaspersoft Studio-6.19.1 by node request. I am using node-jasper package, but when I call my API's request this error appears on the screen
![chrome_AOnnNqmX2z](https://user-images.githubusercontent.com/66263486/222788248-168eb163-d8a7-4919-ba20-bbb3d9301c31.png)
I used lib jasperreports-6.19.1 and Java8:
![Code_uYfUp21yd5](https://user-images.githubusercontent.com/66263486/222788254-a651b879-47b2-487f-a823-1cfb7efb8795.png)

**Comment by Winsgton** [comment]
I also have the same problem and I couldn't solve it.
In jasperstudio it compiles and presents the report, but when I make the request, it shows this error Error running static method\nnet.sf.jasperreports.engine.JRException: Class not found when loading object from file.

If anyone knows and can help, I'd appreciate it!

**Comment by rennan0** [comment]
> I also have the same problem and I couldn't solve it. In jasperstudio it compiles and presents the report, but when I make the request, it shows this error Error running static method\nnet.sf.jasperreports.engine.JRException: Class not found when loading object from file.
> 
> If anyone knows and can help, I'd appreciate it!

I managed to solve the problem by downloading the jar dependencies from the link https://jar-download.com/artifacts/net.sf.jasperreports/jasperreports/6.20.0. Inside my lib folder jasperreports-6.2.0, I created two new folders: dist and lib and put the contents of the downloaded dependencies inside them

**Comment by WagnerAcosta** [comment]
https://www.lachicainformatica.com/2020/01/generacion-de-reportes-en-nodejs-con-node-jasper.html
