### ISSUE TITLE
gyp ERR! stack Error: node-v0.10.37.tar.gz local checksum  not match remote 

### ISSUE THREAD

**Issue by anz000** [agmoyano/node-jasper#8]
I am unable to install node-jasper.
I get the following error:

gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.37.tar.gz local checksum ecbbcf0d18e35bff4d99685fc5ec88fa2adece95702ac0c1d8a4d07655cb38f6 not match remote a5afad14117bb194731e73b4b6635f36950e9476d3873638856cba8dbb4783a5
gyp ERR! stack     at deref (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Linux 3.16.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-jasper/node_modules/java
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by agmoyano** [comment]
Hello @anz000, it seems there's something wrong with your node version.. I've found this http://stackoverflow.com/questions/28385574/error-while-installing-socket-io-by-npm where someone had a similar problem and was adviced the following

> checksum doesn't match. Seems like network corruption. Try installing again, and/or clearing your npm cache
