### ISSUE TITLE
No support for Excel export

### ISSUE THREAD

**Issue by dannyn-mirth** [agmoyano/node-jasper#9]
I'm looking at the source code and I don't see support for Excel xls export.
Doing some research it seems like we need the JRXlsExporter library. Any plans on incorporating Excel export into this?

**Comment by anz000** [comment]
I have the same query. I am already using "node-jasper" for pdf but don't want to switch to another just for Excel support.

**Comment by agmoyano** [comment]
Hi @dannyn-mirth, I don't have it in my plans yet, but any code will be very wellcome!

**Comment by dannyn-mirth** [comment]
I'll give it my best and I'll update you once I have it working!

**Comment by dannyn-mirth** [comment]
Hey, I was able to got it figured out! It's not too hard.

Depending on what version of JasperReports you're using, the code is slightly different.

If you're using JasperReports 5.6.1, then under line 143 add:

self.JRExporterParameter = java.import('net.sf.jasperreports.engine.JRExporterParameter');
self.JRXlsExporter = java.import('net.sf.jasperreports.engine.export.JRXlsExporter');

Next, find the line containing:

self.jem['exportReportTo'+type+'FileSync'](master, tempName);

And replace it with:

var exporter = new self.JRXlsExporter();
exporter.setParameterSync(self.JRExporterParameter.JASPER_PRINT, master);
exporter.setParameterSync(self.JRExporterParameter.OUTPUT_FILE_NAME, tempName);
exporter.exportReportSync();

If you're using JasperReports 6.1.0, import:

self.SimpleExporterInput = java.import('net.sf.jasperreports.export.SimpleExporterInput');
self.JRXlsxExporter = java.import('net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter');
self.SimpleOutputStreamExporterOutput = java.import('net.sf.jasperreports.export.SimpleOutputStreamExporterOutput');

And then use:

var exporter = new self.JRXlsxExporter();
exporter.setExporterInputSync(new self.SimpleExporterInput(master));
exporter.setExporterOutputSync(new self.SimpleOutputStreamExporterOutput(tempName));
exporter.exportReportSync();

I suggest doing a simple if statement to separate the logic between PDF and Excel export.

Sorry I didn't fork and have you do a pull request because I'm very new to this whole Github contribution but I hope that was enough for you to modify this great library to be able to export to Excel! Thanks again for a wonderful library.

**Comment by anz000** [comment]
Hello @dannyn-mirth, I also need to get the xls support up and running. I am quite new to node, and am trying to fix as per your directions, however, am quite lost in the codebase. Could you elaborate clearly how to enable this xls feature. Thank you in advance.
